name:                few
version:             0.1.0.0
github:              "mbrc12/few"
license:             BSD3
author:              "Mriganka Basu Roy Chowdhury"
maintainer:          "mbrc12@gmail.com"
copyright:           "2018 Mriganka Basu Roy Chowdhury"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            A simple file format similar for markdown for writing static text.
# category:            File format

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mbrc12/few#readme>

dependencies:
- base >= 4.7 && < 5
- parsec >= 3
- text >= 1.2

library:
  source-dirs: src

tests:
  few-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - few
